name: Build ZMK Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache west modules
        uses: actions/cache@v3
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: |
          west init -l config
          west update

      - name: West Build (Corne Left)
        run: |
          west build -s zmk/app -p always -b nice_nano_v2 -- -DSHIELD=corne_left -DZMK_CONFIG="/workspace/config"
          mkdir -p artifacts
          cp build/zephyr/zmk.uf2 artifacts/corne_left_nice_nano_v2.uf2

      - name: West Build (Corne Right)
        run: |
          west build -s zmk/app -p always -b nice_nano_v2 -- -DSHIELD=corne_right -DZMK_CONFIG="/workspace/config"
          cp build/zephyr/zmk.uf2 artifacts/corne_right_nice_nano_v2.uf2

      - name: West Build (Corne - both halves in one file)
        run: |
          west build -s zmk/app -p always -b nice_nano_v2 -- -DSHIELD=corne -DZMK_CONFIG="/workspace/config"
          cp build/zephyr/zmk.uf2 artifacts/corne_nice_nano_v2.uf2

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: artifacts/
