name: Build ZMK Firmware

on: [push, workflow_dispatch]

jobs:
  build-left:
    runs-on: ubuntu-latest
    name: Build Left Half
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build left half
        uses: zmkfirmware/zmk-build-action@v1
        with:
          board: nice_nano
          shield: corne_left
          config-dir: config
          artifact-name: corne-left

  build-right:
    runs-on: ubuntu-latest
    name: Build Right Half
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build right half
        uses: zmkfirmware/zmk-build-action@v1
        with:
          board: nice_nano
          shield: corne_right
          config-dir: config
          artifact-name: corne-right
